### ISSUE TITLE
When commands are invalid or when their output has errors, show some warning to indicate failures to the user

### ISSUE THREAD

**Issue by asadhat** [RationaleEmotions/SimpleSSH#4]
```java
ExecResults results = ssh.executeCommand("ls -la");
System.out.println(results.getOutput());
// Able to get the output.

results = ssh.executeCommand("ls- la");
System.out.println(results.getOutput());
 //Empty List !!
			
results = ssh.executeCommand("uname -a");
System.out.println(results.getOutput());
 // Able to get the output.
```

When the above code is executed, the second command does not return any output (because it has errors), but since there are no visible warnings, the user is at a loss on what happened.

**Comment by asadhat** [comment]
"ls- la" command is wrong.

**Comment by krmahadevan** [comment]
I think its a good value add, if we atleast show a warning before returning the output via `executeCommand` whenever there's a return code of `non zero`, so that users are aware of problems (which is what happened in this case). So lets re-open this issue.

**Comment by krmahadevan** [comment]
This is now fixed.
