### ISSUE TITLE
Poolsize error in SCP implementation 

### ISSUE THREAD

**Issue by leonleslie** [RationaleEmotions/SimpleSSH#6]
https://github.com/RationaleEmotions/SimpleSSH/blob/master/src/main/java/com/rationaleemotions/JSchBackedSshKnowHowImpl.java#L143

Shouldn't this line in JSchBackedSshKnowHowImpl read Math.min for the poolSize. This appears that it will run into too many connection type errors. 

`int poolSize = Math.max(MAX_SIZE, localFiles.length);`

**Comment by krmahadevan** [comment]
@leonleslie 
It currently takes the max of 10 or the number of files to be scp'ed to the remote. I agree with you that if one attempts at scp'ing a 1000 files, in one invocation, then it would cause issues.  Thanks for bringing it up. On a side note, would be willing to raise a pull request for the same ?

**Comment by leonleslie** [comment]
First please allow me to thank you for such a great implementation of Jsch and your quick response.  I have used some of your code to refactor some old code from 2014.  Creating a pull request for same.

**Comment by krmahadevan** [comment]
Closed via https://github.com/RationaleEmotions/SimpleSSH/pull/7
